version: "3"
#Backend
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/:/usr/frontend/
      - /usr/frontend/node_modules/
    command: npm start


  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/:/usr/backend
      - /usr/backend/node_modules
    command: npm start